require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemservicosController do

  # This should return the minimal set of attributes required to create a valid
  # Itemservico. As you add validations to Itemservico, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemservicosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all itemservicos as @itemservicos" do
      itemservico = Itemservico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:itemservicos).should eq([itemservico])
    end
  end

  describe "GET show" do
    it "assigns the requested itemservico as @itemservico" do
      itemservico = Itemservico.create! valid_attributes
      get :show, {:id => itemservico.to_param}, valid_session
      assigns(:itemservico).should eq(itemservico)
    end
  end

  describe "GET new" do
    it "assigns a new itemservico as @itemservico" do
      get :new, {}, valid_session
      assigns(:itemservico).should be_a_new(Itemservico)
    end
  end

  describe "GET edit" do
    it "assigns the requested itemservico as @itemservico" do
      itemservico = Itemservico.create! valid_attributes
      get :edit, {:id => itemservico.to_param}, valid_session
      assigns(:itemservico).should eq(itemservico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Itemservico" do
        expect {
          post :create, {:itemservico => valid_attributes}, valid_session
        }.to change(Itemservico, :count).by(1)
      end

      it "assigns a newly created itemservico as @itemservico" do
        post :create, {:itemservico => valid_attributes}, valid_session
        assigns(:itemservico).should be_a(Itemservico)
        assigns(:itemservico).should be_persisted
      end

      it "redirects to the created itemservico" do
        post :create, {:itemservico => valid_attributes}, valid_session
        response.should redirect_to(Itemservico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved itemservico as @itemservico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itemservico.any_instance.stub(:save).and_return(false)
        post :create, {:itemservico => {}}, valid_session
        assigns(:itemservico).should be_a_new(Itemservico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itemservico.any_instance.stub(:save).and_return(false)
        post :create, {:itemservico => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested itemservico" do
        itemservico = Itemservico.create! valid_attributes
        # Assuming there are no other itemservicos in the database, this
        # specifies that the Itemservico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Itemservico.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => itemservico.to_param, :itemservico => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested itemservico as @itemservico" do
        itemservico = Itemservico.create! valid_attributes
        put :update, {:id => itemservico.to_param, :itemservico => valid_attributes}, valid_session
        assigns(:itemservico).should eq(itemservico)
      end

      it "redirects to the itemservico" do
        itemservico = Itemservico.create! valid_attributes
        put :update, {:id => itemservico.to_param, :itemservico => valid_attributes}, valid_session
        response.should redirect_to(itemservico)
      end
    end

    describe "with invalid params" do
      it "assigns the itemservico as @itemservico" do
        itemservico = Itemservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itemservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => itemservico.to_param, :itemservico => {}}, valid_session
        assigns(:itemservico).should eq(itemservico)
      end

      it "re-renders the 'edit' template" do
        itemservico = Itemservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itemservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => itemservico.to_param, :itemservico => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested itemservico" do
      itemservico = Itemservico.create! valid_attributes
      expect {
        delete :destroy, {:id => itemservico.to_param}, valid_session
      }.to change(Itemservico, :count).by(-1)
    end

    it "redirects to the itemservicos list" do
      itemservico = Itemservico.create! valid_attributes
      delete :destroy, {:id => itemservico.to_param}, valid_session
      response.should redirect_to(itemservicos_url)
    end
  end

end
